[package]
authors = ["BurntPizza <xburntpizza@gmail.com>"]
license = "MIT"
name = "aleph"
version = "0.1.0"


[lib]
name = "aleph"

[[bin]]
name = "aleph"
doc = false

[dependencies]
byteorder = "0.5"
itertools = "0.4"
clap = "^2"
ansi_term = "0.7"
hamt = { version = "0.1", git = "https://github.com/michaelwoerister/rs-persistent-datastructures" }
clippy = { version = "0.0", optional = true }

[dev-dependencies]

[features]
default = []