[package]
authors = ["BurntPizza <xburntpizza@gmail.com>"]
license = "MIT"
name = "aleph"
version = "0.1.0"


[lib]
name = "aleph"

[[bin]]
name = "aleph"
doc = false

[dependencies]
itertools = "0.4"
clap = "^2"
ansi_term = "0.7"

[dev-dependencies]
quickcheck = "0.2"